package com.poc.diagnostico.enums;

public enum TipoEnsinoEnum {
    EDUCACAO_INFANTIL,
    ENSINO_FUNDAMENTAL_I,
    ENSINO_FUNDAMENTAL_II,
    ENSINO_MEDIO,
    ENSINO_TECNICO,
    EJA,
    ENSINO_SUPERIOR,
    POS_GRADUACAO,
    EDUCACAO_PROFISSIONALIZANTE,
    EAD,
    EDUCACAO_ESPECIAL,
    ENSINO_TECNICO_INTEGRADO,
    ENSINO_INTEGRAL,
    EDUCACAO_INDIGENA,
    EDUCACAO_QUILOMBOLA;
}
