package com.poc.diagnostico.enums;

public enum TipoEscolaEnum {
    REGULAR,
    EXCLUSIVO_JOVENS_E_ADULTOS,
    EXCLUSIVO_ESPECIAL,
    INSTITUICAO_DE_ATENDIMENTO_COMPLEMENTAR,
    ESCOLA_INDIGENA,
    CONSERVATORIO_ESCOLA_DE_MUSICA,
    ATENDIMENTO_EDUCACIONAL_ESPECIALIZADO,
    ORGANIZACAO_DA_SOCIEDADE_CIVIL_OSC

}
